### ISSUE TITLE
How do i center the installing window on screen

### ISSUE THREAD

**Issue by xwartz** [LinusU/node-appdmg#104]
![](https://cloud.githubusercontent.com/assets/4149827/15449208/bce9da28-1fa9-11e6-9f38-acc388a02722.png)

Screen size is different, so how to center using x/y.

**Comment by LinusU** [comment]
I don't know if this is technically possible, any input appreciated 🙌

**Comment by cstruct** [comment]
@LinusU reading the mozilla wiki it seems to be possible. If the `fwvh` struct is missing `fwi0` defines all edges of the frame rect. I don't know if you could actually do something useful with this since the window would be variable in size.

**Comment by cstruct** [comment]
Closing this since `.DS_Store` doesn't support better centering.
