### ISSUE TITLE
Cannot create DMG with hidden files specified in JSON

### ISSUE THREAD

**Issue by DominikPalo** [LinusU/node-appdmg#113]
I try to use a workaround to move hidden files in DMG outside the initial window, but after I add these files to my JSON config, creating of installer fails on step `[ 5/20] Looking for files...` with error: `Error: ".Trashes" not found at: ...`

I have hidden files specified in JSON as:
```
    { "x": 700, "y": 500, "type": "file", "path": ".background" },
    { "x": 700, "y": 500, "type": "file", "path": ".DS_Store" },
    { "x": 700, "y": 500, "type": "file", "path": ".Trashes" },
    { "x": 700, "y": 500, "type": "file", "path": ".VolumeIcon.icns" }
```

**Comment by LinusU** [comment]
Use `"type": "position"` instead of `"type": "file"`

**Comment by DominikPalo** [comment]
Oh, thanks, it helped... my fail (I overlooked this option for content items)
