### ISSUE TITLE
icon position caching?

### ISSUE THREAD

**Issue by kunkinkan** [LinusU/node-appdmg#116]
Is there some kind of caching going on of DMG positioning? I've change the x and y coordinates but newly created DMG's have the exact same icon position as before.

(and yes i ejected old DMG first).

**Comment by develar** [comment]
Original issue: https://github.com/electron-userland/electron-builder/issues/522

**Comment by LinusU** [comment]
There is no caching going on in appdmg. Can you reproduce this using only appdmg, and not electron builder?

**Comment by develar** [comment]
@kunkinkan Please set env `DEBUG` to `electron-builder` and attach log here.

**Comment by Cha-cho** [comment]
I encountered this problem after repeatedly building then deleting the image. Quitting and restarting the Finder revealed that there was a DMG on my desktop that was previously hidden.

**Comment by cstruct** [comment]
Closing as @kunkinkan hasn't responded in over a year.
