### ISSUE TITLE
Error: JSON Specification not found at: test/assets/appdmg.json

### ISSUE THREAD

**Issue by pfurbacher** [LinusU/node-appdmg#119]
Your "app" seems capable of producing very nice DMGs -- the illustration sure looks nice.

However, when I attempt to run the test suggested in README.md, I get the following:
```
$ appdmg test/assets/appdmg.json ~/Desktop/test.dmg
[ 1/20] Looking for target...                [ OK ]
[ 2/20] Reading JSON Specification...        [FAIL]

Error: JSON Specification not found at: test/assets/appdmg.json
```
Either something is missing from the code in the repository, or in the instructions.

One thing for sure, you assume that the user is a node user. I doubt that would be your target audience (those who are solely interested in making nice looking DMGs, many of whom have no clue as to what node is). Thus, I suggest you reframe your notes in the readme, coming at it as if your primary goal is to make a DMG easily, not as a node-nerd.

**Comment by cstruct** [comment]
Where do you run the command from? The test example, `appdmg test/assets/appdmg.json ~/Desktop/test.dmg`, is meant to be run from the root of this repository.

PRs are welcome if you feel improvements to the README can be made.

**Comment by pfurbacher** [comment]
Thanks, that produces a great looking DMG. 

But I have to say, the readme gives no hint of where it's meant to be run. I'd suggest prefacing the command with the following: 
```
$ cd /usr/local/lib/node_modules/appdmg
```
I'd venture that most users wouldn't know to do that; just experienced noder-coders would.

(I had to search my system to first find ```appdmg.json``` to figure out where it was installed, since I didn't pay attention to the logging during installation.)
