### ISSUE TITLE
Make disk icns differ from app icns

### ISSUE THREAD

**Issue by tresf** [LinusU/node-appdmg#125]
Hi from LMMS!

We're officially switching to appdmg with our 1.2 release and one major difference is that the disk image is the same as the app dmg.  This is OK, but can cause confusion to users (as they may confuse the dmg with the app launcher).

The old (inferior) dmg utilities we used previously always defaulted to the [standard mounted disk icon](https://cloud.githubusercontent.com/assets/6345473/19241177/559e335e-8edb-11e6-91e3-7817ad7a7a15.png) which from a UX perspective we find to be better -- less confusing.

Is there a way to default back to the old default disk image?  Sorry if this is already documented, I couldn't find it in the docs. 👍 

Here's our JSON file: [@lmms/cmake/apple/package_apple.json.in](https://github.com/LMMS/lmms/blob/master/cmake/apple/package_apple.json.in)

**appdmg DMG icon:**
![screen shot 2016-10-10 at 11 16 21 am](https://cloud.githubusercontent.com/assets/6345473/19241080/fda43ed2-8eda-11e6-93f0-ff89014aa2ab.png)

**MacOS App icon:**
![screen shot 2016-10-10 at 11 16 57 am](https://cloud.githubusercontent.com/assets/6345473/19241109/1a02a29e-8edb-11e6-9dd2-93f22c77d19f.png)

**Default MacOS DMG icon**
![screen shot 2016-10-10 at 11 16 58 am](https://cloud.githubusercontent.com/assets/6345473/19241177/559e335e-8edb-11e6-91e3-7817ad7a7a15.png)

**Comment by develar** [comment]
Just not set `icon` :)

**Comment by LinusU** [comment]
Hello! Glad to hear 🙌 

I think that you should be able to just omit the `icon` in the specification. It doesn't affect the app icon, only the dmg icon.

**Comment by tresf** [comment]
> I think that you should be able to just omit the icon in the specification. 

🤕 Of course!  Testing now. :)

**Comment by tresf** [comment]
🎉
