### ISSUE TITLE
Is it possible to change dmg icon by using appdmg

### ISSUE THREAD

**Issue by Kulbear** [LinusU/node-appdmg#126]
Hi all,

I'm using appdmg to package one of my application to .dmg file. I can easily use a DIY icon for my application by setting a .icns file. However, after going through the entire documentation here I didn't find a way to customize my .dmg icon. After the packaging process completed, my .dmg is looks like <img width="84" alt="screen shot 2016-10-10 at 4 00 18 pm" src="https://cloud.githubusercontent.com/assets/14886380/19252554/ae111746-8f02-11e6-843d-1f19303af01f.png">
which is not what I really want.

Is there any possible solution to my case? Any help is appreciated!

**Comment by plrthink** [comment]
I think actually it's just the `icon` option as the doc says: 
> icon (string, optional) - Path to your icon, which will be shown when mounted

Also you can check the code (here)[https://github.com/LinusU/node-appdmg/blob/master/lib/appdmg.js#L296] which indicate that it's the volume icon.
