### ISSUE TITLE
2 questions about title & icons

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [LinusU/node-appdmg#128]
1. Window title contains only icon, title is missing, is there special attribute about this title (window when dmg is mounted)?

2. Is there some way to put icon on dmg file?

**Comment by LinusU** [comment]
Sorry for not getting to this, I'm a bit unsure of the questions, could you try with the latest version (6.0.0), show the steps you have taken, the output you are getting, and what you expected? Happy to re-open this upon answer 👍
