### ISSUE TITLE
Add option to sign DMG

### ISSUE THREAD

**Issue by devAxeon** [LinusU/node-appdmg#134]
Can you add an option to sign the .dmg file giving .provisionfile path argument ?

**Comment by LinusU** [comment]
This would be very nice 👍

**Comment by debelop13** [comment]
I need this also, much thanks!

**Comment by cstruct** [comment]
Fixed and released in 0.5.1

**Comment by feross** [comment]
Pardon the stupid question, as well as bringing this thread back from the dead, but what happens if a DMG is not signed? I've shipped WebTorrent Desktop binaries unsigned for a while now without any issues.

**Comment by LinusU** [comment]
I'm actually not sure since I'm not currently distributing any DMGs, and haven't for a long time 😄 

Would love for anyone to chime in with a response!
