### ISSUE TITLE
install failure

### ISSUE THREAD

**Issue by michaelmou** [LinusU/node-appdmg#137]
npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "appdmg"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1

npm ERR! macos-alias@0.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the macos-alias@0.2.11 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the macos-alias package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs macos-alias
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls macos-alias
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/kugou_mac_dev/.npm/_logs/2017-04-12T02_26_45_174Z-debug.log
insta

**Comment by dominicrico** [comment]
Same here! NodeJS 8.6.0 and NPM 5.5.1
