### ISSUE TITLE
Set user application directory as target

### ISSUE THREAD

**Issue by justechn** [LinusU/node-appdmg#145]
How would I go about setting the user application directory as the target instead of the root application directory

instead of this
`{ "x": 448, "y": 344, "type": "link", "path": "/Applications" },`

i would like 
`{ "x": 448, "y": 344, "type": "link", "path": "/Users/USERNAME/Applications" },`

USERNAME would need to be a variable that would translate to the current user who is installing the app.

I tried `{ "x": 448, "y": 344, "type": "link", "path": "~/Applications" },` but that did not work

**Comment by LinusU** [comment]
Unfortunately, I don't think there's a way to do this.

I'd be happy to re-open if someone can show me a DMG that does this, or provide some insight into how this would be achieved ☺️
