### ISSUE TITLE
Is it possible to build a multi-languages installer?

### ISSUE THREAD

**Issue by tanstry** [LinusU/node-appdmg#157]
Hi

We're deploying our application in English and French languages.
Is there a way to make this drag&drop installer multi-languages?

In fact changing the background image on-the-start can be sufficient.

the process could be:
- detecting OS language
- selecting the background_en or background_fr
- installer is displayed in user's language

**Comment by JakoobCZ** [comment]
+1 this would be a great feature ;)

**Comment by LinusU** [comment]
Unfortunately, I don't think that there is a way to do this. This program only produces DMG-files and has no way to run any code when the image is opened.

Unless there is a way to set different background images for different locales in the ".DS_Store" file format, there is no way for us to do this...

If anyone has any ideas on _how_ to do this, I'd be happy to reopen.
