### ISSUE TITLE
install error ?

### ISSUE THREAD

**Issue by Rensdn** [LinusU/node-appdmg#165]
npm ERR! enoent ENOENT: no such file or directory, access '/usr/local/lib/node_modules/appdmg/node_modules/array-buffer-from-string'

node - 7.9.0
mac

**Comment by LinusU** [comment]
Node.js 7.x is end-of-life and no longer supported. Could you try with Node.js 8 or 10 instead?

**Comment by javaxiu** [comment]
``` shell
node -v
v10.8.0
npm -v
6.5.0
```
got the same question here, could you help me please? thanks a lot

**Comment by LinusU** [comment]
@javaxiu post the error message you are having please ☺️
