### ISSUE TITLE
Install failure under pyenv

### ISSUE THREAD

**Issue by ipconfiger** [LinusU/node-appdmg#171]
`> macos-alias@0.2.11 install /usr/local/lib/node_modules/appdmg/node_modules/macos-alias
> node-gyp rebuild

gyp ERR! configure error
gyp ERR! stack Error: Command failed: /usr/local/var/pyenv/shims/python2 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack pyenv: python2: command not found
gyp ERR! stack
gyp ERR! stack The `python2' command exists in these Python versions:
gyp ERR! stack   2.7.13
gyp ERR! stack   2.7.13/envs/lock27
gyp ERR! stack   lock27`

Seem like can not work well with pyenv

**Comment by LinusU** [comment]
Hey, could you open a bug with node-gyp since this is a upstream problem? Thanks!
