### ISSUE TITLE
Not able to install app dmg in mojave MAC os.

### ISSUE THREAD

**Issue by krupanshu** [LinusU/node-appdmg#172]
Os version 10.14

Getting below error logs.

/usr/local/lib/node_modules/appdmg/node_modules/fs-xattr/.node-gyp/0.12.7/deps/v8/include/v8.h:820:29: note: declared protected here
  static internal::Object** CreateHandle(internal::Isolate* isolate,
                            ^
In file included from ../src/async.cc:2:
../node_modules/nan/nan.h:56:10: fatal error: 'algorithm' file not found
#include <algorithm>
         ^~~~~~~~~~~
1 warning and 2 errors generated.

make: *** [Release/obj.target/volume/src/volume.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:269:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074:12)
gyp ERR! System Darwin 18.0.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/local/lib/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok 
npm ERR! Darwin 18.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appdmg"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! fs-xattr@0.1.17 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fs-xattr@0.1.17 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the fs-xattr package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

**Comment by justinclift** [comment]
Yeah, it looks like one of the dependencies (`node-gyp`) is now broken, and needs to be fixed or replaced.

Without that, appdmg probably isn't going to work. :frowning: 

As a data point, this is also affecting the [DB Browser for SQLite](https://github.com/sqlitebrowser/sqlitebrowser/) nightly builds for macOS.  The nightly build process there reinstalls appdmg (each night) as part of the build process.  Oops. :wink:

**Comment by justinclift** [comment]
This looks like the correct place to report bugs for it: https://github.com/nodejs/node-gyp/issues

**Comment by LinusU** [comment]
should be fixed by #179, in the meantime you can use Node.js 10.x ☺️

**Comment by LinusU** [comment]
Fixed in [🚢 0.6.0](https://github.com/LinusU/node-appdmg/releases/tag/v0.6.0)
