### ISSUE TITLE
Possible to include dependencies?

### ISSUE THREAD

**Issue by DylanC** [LinusU/node-appdmg#175]
My program uses libgraphicsmagick which can be installed manually with brew. Is there a way to bundle this with the Mac .dmg file or get the .dmg to install my dependency as part of the installation process?

**Comment by LinusU** [comment]
Unfortunately for you use case, the dmg is simply a "folder" that can be downloaded. Thus there is no installation step other than the user copying file from this mounted "folder" out to their hard drive.

Maybe you could bundle the file with your binary and have it self-extract it to some good location? 🤔

**Comment by DylanC** [comment]
@LinusU - Thanks, I will have a think about it. Maybe bundle into the binary would be best.
