### ISSUE TITLE
Update xs-attr to 0.3.0 for Node 12 compatibility

### ISSUE THREAD

**Issue by jclark-dot-org** [LinusU/node-appdmg#176]
See also https://github.com/LinusU/fs-xattr/issues/27

(sorry, you closed the fs-xattr bug before I add this as a comment over there)

**Comment by LinusU** [comment]
sorry for the delay on this, should be fixed by #179

**Comment by LinusU** [comment]
Fixed in [🚢 0.6.0](https://github.com/LinusU/node-appdmg/releases/tag/v0.6.0)
