### ISSUE TITLE
DMG packed successfully, but it doesn't seem to be packaged correctly

### ISSUE THREAD

**Issue by SilenceWater** [LinusU/node-appdmg#195]
The script generated DMG successfully. After downloading, the user found that the DMG size was only a few megabytes, but our app should have dozens of megabytes. 
We look forward to hearing from you soon

**Comment by cstruct** [comment]
I'm pretty sure the generated DMG uses zlib compression so a decreased file size is expected. Can you extract the app from the DMG and does it work?
