### ISSUE TITLE
MacOS 12.3 on M1 device: bless: The 'openfolder' is not supported on Apple Silicon devices.

### ISSUE THREAD

**Issue by cybergrind** [LinusU/node-appdmg#204]
Got this error after MacOS update

```
Error: Command failed: bless --folder /Volumes/App --openfolder /Volumes/App
bless: The 'openfolder' is not supported on Apple Silicon devices.
```

**Comment by cybergrind** [comment]
We've tried to assemble dmg without this flag https://github.com/micro-fan/node-appdmg/commit/e4f4edafeeb97fe0273f0bbe526cabe131c8a7bc

And it appears working for both M1 and X86 dmg files.

**Comment by LinusU** [comment]
Interesting, I see a few ways forward:

1. Skip `--openfolder` if `os.arch` is `arm64`, release as patch version
2. Always skip it, release as patch version
3. Always skip it, release as major version

Without knowing more of the background on the flag, it's hard to know wether this is a breaking change or not...

I think that maybe approach 1 would be the best for now?

**Comment by cybergrind** [comment]
It did work on m1 before the update. So it is definitely not hardware limit of m1, probably something was removed from the most recent command line tools or macos.

Will create PR with 1 soon
