### ISSUE TITLE
Fails on M1 systems

### ISSUE THREAD

**Issue by anoopvaidya** [LinusU/node-appdmg#212]
I am using this tool from many years, as soon as I moved to M1 system, I am unable to create dmg.
My project is a Xamarin Mac application.

Attached the error that I see
![appdmgIssue](https://user-images.githubusercontent.com/13703960/181714423-5a59727e-9f98-4322-9077-e73761b99d14.jpg)
.

**Comment by umutocak** [comment]
In order to fix this problem, you need to try with nvm via terminal.

**Comment by LinusU** [comment]
@anoopvaidya it seems like you have installed `appdmg` when running a native arm64 Node.js process, but are then trying to run it under Rosetta.

How are you installing appdmg? How are you executing appdmg?

**Comment by LinusU** [comment]
@anoopvaidya could you try starting it using [`arch`](http://www.manpagez.com/man/1/arch/) to start the arm64 version?

I'm guessing something like:

```
StartProcess("arch", $"-arch arm64 appdmg ./TinyInstaller/appdmg.json ./TinyInstaller/test.dmg");
```
