### ISSUE TITLE
Portable Symbolic Link (alias)

### ISSUE THREAD

**Issue by jamesb93** [LinusU/node-appdmg#213]
Is it possible to have a portable symbolic link made inside the target .dmg? The motivation is to have it so they can drag the contents of the .dmg to a predefined location, somewhere in `~/Library/Application\ Support/REAPER/Scripts`.

Can't seem to make it work with... 

```json
{ "x": 300, "y": 150, "type": "link", "path": "~/"}
```

**Comment by AlexanderOMara** [comment]
A symlink cannot do that in general, `~` is a shell feature.

```sh
$ ln -s '~/' HOME
$ cd HOME
cd: no such file or directory: HOME
```

I don't know is macOS alias's are any different in this regard.

**Comment by jamesb93** [comment]
This was the conclusion I arrived at after researching and trying a bunch of things. Thanks for looking into it for me!

**Comment by LinusU** [comment]
This comment https://github.com/LinusU/node-appdmg/issues/62#issuecomment-263045527 suggests that an alias pointing to `/Users/whatever/...` should work even when the username changes 🤔

**Comment by jamesb93** [comment]
> This comment [#62 (comment)](https://github.com/LinusU/node-appdmg/issues/62#issuecomment-263045527) suggests that an alias pointing to `/Users/whatever/...` should work even when the username changes 🤔

Huh, that is weird! I'll give it a shot
