### ISSUE TITLE
The 'openfolder' is not supported on Apple Silicon devices.

### ISSUE THREAD

**Issue by haochentao** [LinusU/node-appdmg#216]
Error: Command failed: bless --folder /Volumes/appDMG--openfolder /Volumes/appDMG
bless: The 'openfolder' is not supported on Apple Silicon devices.

**Comment by cs-marcoblagoiev** [comment]
I'm running into the same issue. I can confirm that this was working a few months ago on Apple Silicon

**Comment by LinusU** [comment]
Interesting 🤔

I wonder what would happen if we simply skip that flag on Apple Silicon...

**Comment by umutocak** [comment]
Anyone find a solution? This is a huge problem.

**Comment by LinusU** [comment]
Hmm, actually, it seems like this should be fixed by #205 

As you can see here, `--openfolder` shouldn't be called on Apple Silicon:

https://github.com/LinusU/node-appdmg/blob/23d53dccba6e3ca8c9c307912346ad3bfd1903d3/lib/appdmg.js#L403-L405

Which version of appdmg are you using?

**Comment by umutocak** [comment]
I use node-appdmg v0.6.4

**Comment by umutocak** [comment]
the error i got : Command failed: bless --folder /Volumes/Mobile Finder --openfolder /Volumes/Mobile Finder
bless: The 'openfolder' is not supported on Apple Silicon devices.

It gets stuck in the Blessing image... section.

**Comment by LinusU** [comment]
@umutocak are you running Node.js under Rosetta?

**Comment by umutocak** [comment]
yes, i closed rosetta and appdmg re-installed. This time it worked. Thank you

**Comment by LinusU** [comment]
Closing as fixed in https://github.com/LinusU/node-appdmg/pull/205
