### ISSUE TITLE
why create temp file in my macos framework dir?

### ISSUE THREAD

**Issue by toby20130333** [LinusU/node-appdmg#217]
Hi support

In the last packaging, it was found that a hidden file was added to the directory Framework in the installation package. Is this packaging script poisoned? hidden name is : .BC.T_lbSnA3?
Or something else?

**Comment by LinusU** [comment]
Are you sure that this is from appdmg?

Do you have any steps on how to reproduce this?

**Comment by toby20130333** [comment]
The problem has been solved
I will clean up all the dmg stored previously and the directory to be packaged, and it will be OK to start again
thank you
I think this hidden file is a temporary cache file in the packaging process?
There may be a phase error in the packaging process, but the temporary cache is not cleared

**Comment by LinusU** [comment]
> I think this hidden file is a temporary cache file in the packaging process?

I don't think that the file is being created by appdmg?

**Comment by LinusU** [comment]
I don't know about other packages, but I have seen no evidence of anything like that in appdmg...

**Comment by toby20130333** [comment]
I mean the depends package?
