### ISSUE TITLE
Security Prototype Pollution in 'async'

### ISSUE THREAD

**Issue by Mgrdich** [LinusU/node-appdmg#235]
A vulnerability exists in Async through 3.2.1 (fixed in 3.2.2), which could let a malicious user obtain privileges via the mapValues() method.

[Here is the link](https://github.com/advisories/GHSA-fwr7-v2mv-hh25)

**Comment by LinusU** [comment]
<img width="183" alt="Screenshot 2023-11-28 at 14 15 43" src="https://github.com/LinusU/node-appdmg/assets/189580/0fd4a6f9-51b2-42f6-a434-7c46638712f5">

As far as I can tell from your link, this does not affect version 1.x of `async`, which is what we are using:

https://github.com/LinusU/node-appdmg/blob/bb0f693a74341fda7934b42fd0adcb37022f6e05/package.json#L9

Or am I missing something?

**Comment by Mgrdich** [comment]
yep my bad. @LinusU
