### ISSUE TITLE
Hide File Extension

### ISSUE THREAD

**Issue by byronclark** [LinusU/node-appdmg#36]
It would be great to allow hiding the file extension for files in the dmg.

**Comment by LinusU** [comment]
> If you select “Show all filename extensions,” all extensions are shown, even for files that have “Hide extension” selected. If you deselect “Show all filename extensions,” then file extensions are shown or hidden based on their individual “Hide extension” settings.

http://support.apple.com/kb/PH19072

---

I actually think that this is a bit out of the scope of this program. If you want the file extensions to be hidden (for people with "Show all filename extensions" turned off) than you could right click the file to be included and choose `Get Info` -> `Name & Extension` -> `Hide extension`.

If that dosen't work (e.g. `cp -r` dosen't copy extended attributes) than we can reopen this as `Extended attributes is not preserved`.
