### ISSUE TITLE
Do you have a plan to develop a Grunt plugin for appdmg?

### ISSUE THREAD

**Issue by htanjo** [LinusU/node-appdmg#43]
Not an issue, but a question.

I'm developing a [Grunt](http://gruntjs.com/) plugin using the node-appdmg API.
It runs appdmg via `grunt` command and Gruntfile.js.
https://github.com/rakuten-frontend/grunt-appdmg

Do you have a plan to develop such a Grunt plugin?
If not, I will publish it from my account.

Thanks for providing this useful module!

**Comment by unindented** [comment]
@LinusU what's the expected release date for `0.3.0`? I'd love it if we could provide config objects directly, without the need for a temporary file.

**Comment by LinusU** [comment]
@unindented All paths are relative to the json-file which is something to take into consideration. How are you using it? Would this affect you?

@htanjo I see that you traverse all the path-related options and make them absolute. I'm thinking it would be better if you didn't have to do that...

Maybe something like this could be it, what do you think?

```javascript
appdmg({
  basepath: '/tmp/test/',
  specification: { ... },
  target: '/tmp/test.dmg'
});
```

**Comment by unindented** [comment]
@LinusU Right now I'm creating a temp file with `node-tmp` in the project folder, so I haven't been bitten by path problems.

Providing a base path seems like a nice solution, but I'll let @htanjo chime in.

**Comment by htanjo** [comment]
Sounds good! `basepath` option is really helpful.

**Comment by unindented** [comment]
@LinusU, @htanjo I've created a couple of pull requests to get the ball rolling. Feel free to modify as necessary:

* https://github.com/LinusU/node-appdmg/pull/52/files
* https://github.com/rakuten-frontend/grunt-appdmg/pull/1

**Comment by LinusU** [comment]
I guess that this is resolved now, feel free to reopen otherwise

**Comment by htanjo** [comment]
Yes, resolved.
@LinusU, @unindented, thanks for your help!
