### ISSUE TITLE
Hidden Folders are displayed

### ISSUE THREAD

**Issue by gerwinbrunner** [LinusU/node-appdmg#45]
Hi,

I just tried out you module and I think it is really awesome! Thanks a lot.

I ran just into one small issue and I'm not sure what I can do about it.
I can build a dmg without a problem based on your sample (test)

The storage thing is, that when I mount the dmg everything is fine, only all the hidden files are display.
i.e.: .background, .Trashes, ...

Do you have any idea what I can do to prevent this?

Thanks,
Gerwin

![screen shot 2014-11-01 at 19 30 07](https://cloud.githubusercontent.com/assets/75502/4872850/b0c06352-61f5-11e4-9a11-4780c12cc05e.png)

**Comment by pietergunst** [comment]
Some of the costumers will have this hidden files display property enabled as well. I noticed Firefox just moves these hidden files outside the initial window size. Is there any way to this with your program?

**Comment by LinusU** [comment]
Hmm, that's a quite hacky way... But maybe it could work.

It's not really supported right now but it's very easy to fix. Maybe we should just do this for all images that `appdmg` creates.

The positions could be at: `x: (n * iconSize), y: height`, `n` is the index. `'.background', '.DS_Store', '.VolumeIcon.icns', '.Trashes'` would probably the complete list.

It would be added to [appdmg.js line 393](https://github.com/LinusU/node-appdmg/blob/master/lib/appdmg.js#L393).

**Comment by mmastrac** [comment]
I patched my local copy to put the icons for those four items at 0,0. It's not ideal, but I can't imagine many people show hidden files like I do.

**Comment by LinusU** [comment]
@mmastrac Try putting them outside the view instead of at 0,0. Then they shouldn't be visible unless you resize the window.

**Comment by andreaslarsen** [comment]
@mmastrac can you post your local copy somewhere - I'd like to fix this :)

**Comment by LinusU** [comment]
@andreaslarsen Add the following lines at [line 393 in appdmg.js](https://github.com/LinusU/node-appdmg/blob/master/lib/appdmg.js#L393).

```javascript
ds.setIconPos('.background', 0, 1024);
ds.setIconPos('.DS_Store', 64, 1024);
ds.setIconPos('.VolumeIcon.icns', 128, 1024);
```

**Comment by andreaslarsen** [comment]
@LinusU Thx, I'm having some issues though

This is prior to adding it:

![screen shot 2015-04-22 at 15 11 23](https://cloud.githubusercontent.com/assets/3859425/7275058/fef6f3e0-e901-11e4-9bfe-fed769ec2213.png)

This is after adding `ds.setIconPos('.background', 0, 1024);`

![screen shot 2015-04-22 at 15 12 21](https://cloud.githubusercontent.com/assets/3859425/7275091/2a238722-e902-11e4-99a5-d4a7bd93027c.png)

**Comment by andreaslarsen** [comment]
What could be cool was to make the background 100 px taller than needed and then from line 383
```
    ds.setWindowSize(global.bkgsize[0], global.bkgsize[1]-100);

    global.opts.contents.forEach(function (e) {
      ds.setIconPos(path.basename(e.path), e.x, e.y);
    });

    ds.write(path.join(global.temporaryMountPath, '.DS_Store'), function (err) {
      next(err);
    });

    ds.setIconPos('.background', 0, global.bkgsize[1]-50);
    ds.setIconPos('.DS_Store', 64, global.bkgsize[1]-50);
    ds.setIconPos('. VolumeIcon.icns', 128, global.bkgsize[1]-50);
```
or something like it

**Comment by LinusU** [comment]
Hmm, that looks like a problem with ds-store that we ran into before, I thought that was fixed though...

Could you try to only add one of the lines, say `.background` and comment out the other two?

Re. the background. Why make it larger? Since that will be outside the window size anyway? What we should do is replace `1024` with `global.bkgsize[1]`.

Also, it seems like there is an erroneous space inserted in the last line you posted.

**Comment by andreaslarsen** [comment]
The difference between the two images is, as I also wrote earlier :wink: ,  `ds.setIconPos('.background', 0, 1024);`

**Comment by andreaslarsen** [comment]
the background should be larger because when the icons are moved down the user can also scroll down.

Dropbox does it for their dmg

Firefox doesn't

**Comment by andreaslarsen** [comment]
It's probably easier to not make the background bigger. 

But should the y-postion then be global.bkgsize[1] + .5 icon size ?

**Comment by LinusU** [comment]
Sorry, I missed that. Could you try with only `.DS_Store`?

I didn't realise that the user would be able to scroll, but of course they will... That's annoying :(

And yes they should be `global.bkgsize[1] + .5 icon size`, then they would be just outside of view :)

I think that requiring everyone to make larger backgrounds feels very wrong since most people don't have hidden files turned on. I honestly don't know how to deal with this problem... Thoughts are very welcome!

**Comment by andreaslarsen** [comment]
I don't think anything better can be done - otherwise e.g. Firefox and Dropbox would surely do so.

I think adding ´global.bkgsize[1] + .5 icon size´ is a good idea. 

And if you add a boolean to the json file called myBackIsBig

and then 
```
if (myBackIsBig) {global.bkgsize[1]-=100) } 
```
then it won't affect people using this tool who haven't created a bigger background

**Comment by andreaslarsen** [comment]
I'm still having problems with the icons. This is by adding only `    ds.setIconPos('.DS_Store', 64, 1024);
`
![screen shot 2015-04-22 at 18 41 05](https://cloud.githubusercontent.com/assets/3859425/7279848/273eb01e-e91f-11e4-8640-923f458b74f6.png)

**Comment by mmastrac** [comment]
My patch was:

     ds.setIconSize(global.opts['icon-size']);
     ds.setBackground(path.join(global.temporaryMountPath, global.bkgname));
     ds.setWindowSize(global.bkgsize[0], global.bkgsize[1]);
    + ds.setIconPos('.VolumeIcon.icns', 0, 0);
    + ds.setIconPos('.background', 0, 0);
    + ds.setIconPos('.DS_Store', 0, 0);
    + ds.setIconPos('.Trashes', 0, 0);

**Comment by iRobertas** [comment]
In 0.30

+ ds.setIconPos('.VolumeIcon.icns', 0, 0);
+ ds.setIconPos('.background', 0, 0);
+ ds.setIconPos('.DS_Store', 0, 0);
+ ds.setIconPos('.Trashes', 0, 0);

Works for me to.

**Comment by LinusU** [comment]
Trying to think outside the box, would it be possible to assign an empty icon to all the hidden files? But maybe this is pushing it...

I think that I could accept putting the icons at `0,0`, it seems like a fair tradeoff.

**Comment by andreaslarsen** [comment]
i don't think you can do the empty icon thing since ds_store needs to be there anyway

**Comment by andreaslarsen** [comment]
I ended up moving the icons out of the view to the right (assuming a user is less likely to scroll horizontally)

Putting the ```ds.setIconPos...```where @mmastrac told fixed the arranging problems I had.

![screen shot 2015-04-24 at 14 29 15](https://cloud.githubusercontent.com/assets/3859425/7318641/53f15c68-ea8e-11e4-952b-aac25982312b.png)
![screen shot 2015-04-24 at 14 29 22](https://cloud.githubusercontent.com/assets/3859425/7318642/5412c2a4-ea8e-11e4-9762-a7a04f8c4cc5.png)

**Comment by LinusU** [comment]
That's a sweet looking installer! Out of curiosity, have you tried downloading that dmg from the internet, then mounted and started the installer? It seems like it should have the same issues as in #56, but we never got to a conclusion on wether it was appdmg that was to blame or not.

Having them to the right is quite sweet :) If we can figure out a clean api for this, I would be happy to merge in a patch. Any suggestions for how it should look in the json file?

**Comment by andreaslarsen** [comment]
Thanks. Just up/download to test - looks good. 
Try yourself https://dl.dropboxusercontent.com/u/3019777/FontForge%20Installer%202.dmg

**Comment by LinusU** [comment]
Works great, thank you!

**Comment by andreaslarsen** [comment]
Yep, only "quirk" being the empty name in the warning dialog - not sure how to fix that.

**Comment by LinusU** [comment]
I think it's because the app file is named `".app"`. Which reminds me, this is how it looks on my computer, I have "always show file extension" checked.

![screen shot 2015-04-24 at 16 04 27](https://cloud.githubusercontent.com/assets/189580/7320246/991afd14-ea9b-11e4-8f85-40227a2f56ba.png)

**Comment by andreaslarsen** [comment]
Yep - because I wanted the clean look...was hoping for a hack fix ;)

**Comment by andreaslarsen** [comment]
I don't know any node but I have an idea that may work. Will pr you something unfinished if you want to have a look?

**Comment by andreaslarsen** [comment]
https://github.com/andreaslarsen/node-appdmg/tree/hide-hidden-icons

**Comment by andreaslarsen** [comment]
@LinusU still interested in fixing this? https://github.com/LinusU/node-appdmg/compare/master...andreaslarsen:hide-hidden-icons

**Comment by andreaslarsen** [comment]
don't know if you're still interested in fixing this but the prettiest dmg I've seen to date is  https://affinity.serif.com/en-gb/designer/trial/ 

They make it very long so that the short scroll bar gets hidden in the dark background in the top of the window.

**Comment by LinusU** [comment]
Hmm, that's quite clever

![screen shot 2015-05-26 at 22 45 33](https://cloud.githubusercontent.com/assets/189580/7822935/167f8eac-03f9-11e5-9a5a-7e54eff8d31a.png)

They don't have a larger background thought.

I'm sorry for not giving this any attention but I'm not satisfied with the solution in your patch. (also, it isn't working so I need to fix that first)

I want to support this in the best way possible and maybe that is to position them far far down like in the dmg you linked. I don't want people to need to make a different background thought...

**Comment by andreaslarsen** [comment]
No worries - my patch was just an unfinished draft.

You can do the same as affinity without the background - just position them way, way down to make the scrollbar as small as possible.

**Comment by teleclimber** [comment]
> just position them way, way down to make the scrollbar as small as possible.

I don't think this is a good idea. If a user accidentally scrolls a bit their folder will look like it is blank (nothing in it).

**Comment by teleclimber** [comment]
Is there still interest in fixing this? I am having this issue because I show my hidden files and I suspect others do as well.

Before trying appdmg I played with [create-dmg](https://github.com/andreyvit/create-dmg) which gives the option to position icons that are in the DMG. So my command included this:

```
--icon ".Trashes" 100 600 --icon ".VolumeIcon.icns" 400 600 --icon ".background" 100 800
```

Why couldn't we add that capability to appdmg and everybody could position icons wherever they think is best to get around this problem?

**Comment by teleclimber** [comment]
> Why couldn't we add that capability to appdmg and everybody could position icons wherever they think is best to get around this problem?

Huh, it turns out we can! I followed the code path and realized `type` is not being checked for invalid types, `file` and `link` types get their own code path, yet all things listed in contents have their icons moved in the `Making all the visuals` step.

So if you put this in your config's `contents`:
```
{ "x": 50, "y": 400, "type": "position", "path": ".background" },
{ "x": 100, "y": 400, "type": "position", "path": ".DS_Store" },
{ "x": 150, "y": 400, "type": "position", "path": ".Trashes" },
{ "x": 200, "y": 400, "type": "position", "path": ".VolumeIcon.icns" }
```
...those pesky hidden icons get moved down and out of view. (Adjust positions to fit your situation.)

**Comment by LinusU** [comment]
Hehe, that's cool, but I would not recommend relying on undocumented features. We could probably add a type for the "special" files that already exists.

What do you think is a good name for the type? `special`, `position`, `system`... Suggestions?

**Comment by teleclimber** [comment]
I think `position` is good because that is all that is happening here. In the docs we should be clear that these icons are added no matter what (unlike the other types in `contents`) but that you can specify where they go.

**Comment by kdawgwilk** [comment]
:+1:
