### ISSUE TITLE
hdiutil Error code 1

### ISSUE THREAD

**Issue by maxpavlov** [LinusU/node-appdmg#47]
When I am running the app with what it seems to be a correct input, I get:

[ 1/20] Looking for target...                [ OK ]
[ 2/20] Reading JSON Specification...        [ OK ]
[ 3/20] Parsing JSON Specification...        [ OK ]
[ 4/20] Validating JSON Specification...     [ OK ]
[ 5/20] Looking for files...                 [ OK ]
[ 6/20] Calculating size of image...         [ OK ]
[ 7/20] Creating temporary image...          [FAIL]

Error: Error running `hdiutil`! Exit code was 1

Macbook Pro Retina, using the provided TestBkg.png. OS is Yosemite 10.10.1

Any hints would be very appreciated.

**Comment by maxpavlov** [comment]
After restart the problem went away and I was able to proceed all the way up to step 16 and then an absolutely non-informative message poped as an error:

[ 1/20] Looking for target...                [ OK ]
[ 2/20] Reading JSON Specification...        [ OK ]
[ 3/20] Parsing JSON Specification...        [ OK ]
[ 4/20] Validating JSON Specification...     [ OK ]
[ 5/20] Looking for files...                 [ OK ]
[ 6/20] Calculating size of image...         [ OK ]
[ 7/20] Creating temporary image...          [ OK ]
[ 8/20] Mounting temporary image...          [ OK ]
[ 9/20] Making hidden background folder...   [ OK ]
[10/20] Copying background...                [ OK ]
[11/20] Reading background dimensions...     [ OK ]
[12/20] Copying icon...                      [ OK ]
[13/20] Setting icon...                      [ OK ]
[14/20] Creating links...                    [ OK ]
[15/20] Copying files...                     [ OK ]
[16/20] Making all the visuals...            
AssertionError: false == true

**Comment by krainboltgreene** [comment]
Restarting didn't solve it for me :(

**Comment by dermeister0** [comment]
I got the error because output directory did not exist.
