### ISSUE TITLE
Please add support for bzip2 compression

### ISSUE THREAD

**Issue by oxtoacart** [LinusU/node-appdmg#54]
Starting with OS X 10.4, hdiutil supports the format `UDBZ`.  On my app, this form reduces the size of the resulting package by 8%, which is nothing to sneeze at.

**Comment by oxtoacart** [comment]
BTW, thanks for an awesome tool!

**Comment by LinusU** [comment]
That would be cool! Could be specified with `"compression": "UDBZ"`. Other valid values would be `UDZO` and `NONE`.

Pull request welcome!
