### ISSUE TITLE
Path resolve not handling back-tracking paths

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [LinusU/node-appdmg#55]
The path resolving of `contents` does not allow for back-tracking paths, eg. `"../../Folder/file.app"` will not work.

In my case, I would like to have the `.json` file indicating my dmg package in it's own folder with some of the stuff I need for this, and I have the following which does not work:

    //...
    "contents": [
      { "x": 192, "y": 344, "type": "file", "path": "../dist/MyApp/osx64/MyApp.app" },
    //...

**Comment by LinusU** [comment]
Could you please attach the output from the command, it should say something like `"..." not found at: ...`.

**Comment by stephan-nordnes-eriksen** [comment]
I made a workaround for my project, and I don't have the exact layout as before. I am trying to reproduce the issue, but can't seem to do it. I really suspect I had a **typo** or something. If that is the case, sorry for bothering you :)

Keep up the great work! Love the module :)

**Comment by LinusU** [comment]
No problem, it uses `path.resolve()` internally so it should work with relative paths.
