### ISSUE TITLE
Dropbox and DMG filesystem format

### ISSUE THREAD

**Issue by sandvige** [LinusU/node-appdmg#56]
Hello,

We're using appdmg to build our DMG file, but it appears there's a few quirks when running the final DMG file.

We're trying to create a Dropbox like DMG file, which contains an Application Bundle you can directly execute from the DMG ( https://www.dropbox.com/download?plat=mac ), but when we're doing it from the generated DMG file from appdmg, this is not behaving the same way the Dropbox installer does.

Since the file is downloaded from Internet, the quarantine extended attribute is added to the DMG file, and when Mac mount the DMG, the quarantine flag is added to the mount point:
```
mini-sandvige:bin Sandvige$ mount
/dev/disk1 on / (hfs, local, journaled)
devfs on /dev (devfs, local, nobrowse)
map -hosts on /net (autofs, nosuid, automounted, nobrowse)
map auto_home on /home (autofs, automounted, nobrowse)
/dev/disk3s1 on /Volumes/MyApplication Installer (hfs, local, nodev, nosuid, read-only, noowners, quarantine, mounted by sandvige)
/dev/disk4 on /Volumes/Dropbox Installer (cd9660, local, nodev, nosuid, read-only, noowners, quarantine, mounted by sandvige)
``` 

At this point, everything is normal, and when I double click on the Application Bundle, I have the security popup asking if I can trust this application or not. If I hit yes, the Dropbox application starts, and the DMG closes. But when I double click on my application, the security popup ask the same thing, and if I click "Yes", nothing happens. I have to click on the "Always trust this DMG file" checkbox.

The only difference I've been able to notice is the filesystem format, which is HDF for appdmg, and cd9660 for the Dropbox one.

Have you ever heard about something like that?

Thanks :)

**Comment by LinusU** [comment]
It seems like they are using the same file format that is commonly found on cds inside the dmg file. If you can figure out how to create one, preferably using `hdiutil`, it shouldn't be too hard to add it.

**Comment by sandvige** [comment]
I wasn't able to successful patch appdmg to achieve that, but I'm wondering if the format is responsible of this behavior, and if so, why?

**Comment by LinusU** [comment]
I don't think that the format is responsible for that, but I haven't done enough research too say for sure.

You could try to take the dropbox application bundle and package it thru `appdmg`, then you'll know if the problem is with `appdmg` or with your application bundle.

**Comment by LinusU** [comment]
I have now tried this with another dmg and it dosen't exhibit the same problem. I'll have to assume that this is problem with your app file.

Feel free to reopen this if there is more information or if you follow the instructions in my latest comment. Thank you for your time :)
