### ISSUE TITLE
osx 10.6 displays the @2x image

### ISSUE THREAD

**Issue by andreaslarsen** [LinusU/node-appdmg#58]
osx 10.6 doesn't seem to like the tiff package

![screen shot 2015-04-24 at 14 29 15](https://cloud.githubusercontent.com/assets/3859425/7318668/ac85d9da-ea8e-11e4-9ee0-b00254046912.png)
![37d1ffb0-e9fd-11e4-90bd-4fb1faf1a317](https://cloud.githubusercontent.com/assets/3859425/7318670/affae0ce-ea8e-11e4-9d6f-b798bb82f421.png)

**Comment by dliessi** [comment]
Duplicate of #32.

**Comment by andreaslarsen** [comment]
cheers, only looked in active issues

**Comment by LinusU** [comment]
> As of February 26, 2014 Mac OS X 10.6 is no longer officially supported so I don't think that I will take any action to fix this. If someone makes a clean pull request I will merge it but otherwise this will be a wontfix.
