### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by malavagile** [LinusU/node-appdmg#60]
Hello 

I am trying to use your library to create a DMG file from my .app file.
I read out your Documentation regarding how can I use that but still it's not working for me.
When I try to run the installation command it's giving below message

sh-3.2$ install -g appdmg
usage: install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 file2
       install [-bCcpSsv] [-B suffix] [-f flags] [-g group] [-m mode]
               [-o owner] file1 ... fileN directory
       install -d [-v] [-g group] [-m mode] [-o owner] directory ...
sh-3.2$ 

I am sure I am doing something wrong but not able to figure it out.
Can anyone help me in this?

**Comment by DomT4** [comment]
You seem to be missing the `npm` from the command? Should be ` npm install -g appdmg `.

**Comment by malavagile** [comment]
sh-3.2$ npm install -g adddmg
sh: npm: command not found

This is what i get with npm

**Comment by DomT4** [comment]
Then you need to install Node & `npm`. What platform are you using?

**Comment by malavagile** [comment]
I am on MAC OS Yosemite

**Comment by DomT4** [comment]
If you use Homebrew, `brew install node`. If you use MacPorts, `port install nodejs`. If you use neither, grab the `.pkg` from https://nodejs.org/download/ and install that. Afterwards, ensure `which node` shows something in your shell, and presuming it does you should be able to do `npm install -g appdmg` then.

**Comment by malavagile** [comment]
I received below message from terminal

npm install -g appdmg
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "appdmg"
npm ERR! node v0.12.3
npm ERR! npm  v2.9.1
npm ERR! path /usr/local/lib/node_modules/appdmg
npm ERR! code EACCES
npm ERR! errno -13

npm ERR! Error: EACCES, unlink '/usr/local/lib/node_modules/appdmg'
npm ERR!     at Error (native)
npm ERR!  { [Error: EACCES, unlink '/usr/local/lib/node_modules/appdmg']
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   path: '/usr/local/lib/node_modules/appdmg' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.
npm ERR! error rolling back Error: EACCES, unlink '/usr/local/lib/node_modules/appdmg'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EACCES, unlink '/usr/local/lib/node_modules/appdmg']
npm ERR! error rolling back   errno: -13,
npm ERR! error rolling back   code: 'EACCES',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/appdmg' }

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/agilepc2/npm-debug.log

**Comment by DomT4** [comment]
If you're using Node installed from the `.pkg` you'll need to use `sudo`.

**Comment by malavagile** [comment]
there is one file in zip called appdmg in bin folder do I have to put that somewhere?

I tried sudo and received this

gyp WARN EACCES user "root" does not have permission to access the dev dir "/Users/agilepc2/.node-gyp/0.12.3"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/local/lib/node_modules/appdmg/node_modules/ds-store/node_modules/macos-alias/.node-gyp"
\

**Comment by DomT4** [comment]
This is why I hate `.pkg` Node :smile_cat:.

There should be a simple `appdmg` binary in `/usr/local/bin` after `sudo npm install -g appdmg`. Try starting afresh here, do `sudo rm -rf /usr/local/lib/node_modules/appdmg `. For the `node-gyp` error try `sudo chown -R root ~/.node-gyp`. After that try the installation command again.

**Comment by malavagile** [comment]
not worked here..... I guess I used .pkg file that's the problem?

**Comment by LinusU** [comment]
I would really recommend you to use [Homebrew](https://brew.sh/) instead of the `.pkg`. It should cause you way less headache.

Other than that I can only recommend you to follow @DomT4 latest post (thanks for the help!), did you do all the steps that he posted? What is it that didn't work?

**Comment by malavagile** [comment]
Okey I installed the Homebrew now what's the next step can you help me to make npm command work.

**Comment by LinusU** [comment]
Assuming Homebrew is installed:

```sh
brew install node
```

You should then be able to install appdmg:

```sh
npm install -g appdmg
```

And then run it:

```sh
appdmg spec.json output.dmg
```

**Comment by DomT4** [comment]
If you're switching from the `.pkg` to Homebrew I'd advise pretty much wiping out the entire `npm` installation first:

```
#!/bin/sh
sudo rm -r ~/.node
sudo rm -r ~/.npm
sudo rm -r ~/.node-gyp
sudo rm -r ~/.npmrc
sudo rm -r ~/node_modules
sudo rm /usr/local/bin/node
sudo rm /usr/local/bin/npm
sudo rm -r /usr/local/include/node
sudo rm -r /usr/local/lib/node_modules
sudo rm -r /usr/local/lib/dtrace
sudo rm -r /usr/local/share/systemtap
sudo rm /usr/local/share/man/man3/npm-*
sudo rm /usr/local/share/man/man3/npm.3
sudo rm /usr/local/share/man/man1/node.1
sudo rm /usr/local/share/man/man1/npm-*
sudo rm /usr/local/share/man/man1/npm.1
sudo rm /usr/local/share/man/man5/npm-*
sudo rm /usr/local/share/man/man5/npmrc.5
sudo rm /usr/local/share/man/man7/npm-*
sudo rm /usr/local/share/man/man7/removing-npm.7
find -L /usr/local/bin -type l -exec rm -i {} +
sudo chown -R `whoami` /usr/local
```

There are (many) more compact ways, but essentially that's everything you would want to do. The Node installed via `.pkg` has some very troublesome permissions set which `brew` can't override (because `brew` doesn't run as root, and generally refuses to replace files it didn't put there in the first place). It's easier to start from a clean slate.

**Comment by LinusU** [comment]
@malavagile please reopen if your problem persists
