### ISSUE TITLE
links to ~/path are not supported?

### ISSUE THREAD

**Issue by Sega-Zero** [LinusU/node-appdmg#62]
trying to put a link to `~/Library/` for example:<br>
`{ "x": 430, "y": 140, "type": "link", "path": "~/Library/" },`
and the result dmg shows it without icon: <br>![500px screensaver 2015-06-07 17-58-17](https://cloud.githubusercontent.com/assets/2203199/8024503/cabfe882-0d3e-11e5-968c-cd00a591dafe.jpg) <br>
and does not open on double-click. Is this a misconfig or a bug?

**Comment by LinusU** [comment]
Good question, I need to do some investigation here. It will depend on wether Mac OS Aliases supports it or not...

**Comment by LinusU** [comment]
Closing this since I think that this is a limitation with aliases (and links) on Mac OS X (and UNIX)

**Comment by randomeizer** [comment]
Aliases do support it, but I think the mechanism is that an alias is created pointing at an absolute path for the current user. For example, if I'm user 'foobar', `~/Library` becomes `/Users/foobar/Library`. Then, when accessing this link, macOX will then redirect it automatically to the current user.
