### ISSUE TITLE
Better error message when target directory isn't present

### ISSUE THREAD

**Issue by fritx** [LinusU/node-appdmg#65]
![image](https://cloud.githubusercontent.com/assets/6647633/9299136/3301feba-44eb-11e5-8e5f-bf271a2ef267.png)

i found that it was the directory of the dmg target path didn't exist
i think it's a little strange with that outcoming message

how about we making sure the target directory is created, using `mkdirp` or something? :)

**Comment by LinusU** [comment]
As I said in #63, I'm not sure that we should create the output directory.

> Hmm, I'm actually not sure if it should be `appdmg`s responsibility to make sure that the output folder exists. I don't know of any other unix commands that does it. E.g.

> ```text
$ echo 'test' > /tmp/no-exists/my-file 
zsh: no such file or directory: /tmp/no-exists/my-file

>$ touch /tmp/no-exists/my-file 
touch: /tmp/no-exists/my-file: No such file or directory

>$ cp linus.jpg /tmp/no-exists/my-file
cp: /tmp/no-exists/my-file: No such file or directory

>$ cat test.c 
int main(void) { return 0; }
$ gcc -o /tmp/no-exists/my-file test.c 
ld: can't open output file for writing: /tmp/no-exists/my-file, errno=2 for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

> Now, I would like a much better error output thought. I think that the best way here is to try and create the file earlier on, and then raise helpful error if something goes wrong, and then tell `hdiutil` to overwrite the created empty file. This prevents ant race conditions that other approaches might have (e.g. checking if the directory exists, then starting hdiutil).

That being said, a better error message would be very appropriate.

**Comment by fritx** [comment]
oops sorry for the duplicated issue :)
entirely agreed. then how about checking the `source`/`target` before the hdiutil call?
i'm not sure it is good or not though

**Comment by LinusU** [comment]
I think that the best solution would be to start by creating `target` with the `O_EXCL` flag. That way we ensure that the file can be created; and error out early if something goes wrong.
