### ISSUE TITLE
fs-xattr dependency is incompatible with nan 2.x

### ISSUE THREAD

**Issue by ducky427** [LinusU/node-appdmg#66]
Could you please update the version of `fs-xattr` so that it can be used with nan v2.x and io.js v3.1. I see that you have already upgraded `fs-xattr` for the new nan.

Thanks!

**Comment by ducky427** [comment]
I think my issue is deeper than that. Looks like `node-gyp` isn't compatible with io.js 3.0. Issue here nodejs/node-gyp#685

**Comment by LinusU** [comment]
The dependency is specified as `~0.1.4` so that will install version `0.1.11` which is the one using nan 2.x so that shouldn't be the problem.

I think, as you said, that the issue is with node-gyp. Feel free to reopen if any action is needed from my side.

**Comment by ducky427** [comment]
Thanks a lot!
