### ISSUE TITLE
Do I have to set background image?

### ISSUE THREAD

**Issue by laike9m** [LinusU/node-appdmg#69]
I've used other dmg packaging tool for a while and switched to node-appdmg now. Previous tools don't force me to put a background image, but it seems this is necessary for appdmg?

If I remove the `background` line, it gives me an error:
```
[ 1/20] Looking for target...                [ OK ]
[ 2/20] Reading JSON Specification...        [ OK ]
[ 3/20] Parsing JSON Specification...        [ OK ]
[ 4/20] Validating JSON Specification...     [FAIL]
[FAIL]

Error: `background`,`contents.0.x` missing from JSON Specification
```

**Comment by LinusU** [comment]
Hmm, yes I guess it is. It should be fairly easy to make it optional thought, pull request welcome.

**Comment by LinusU** [comment]
No longer mandatory as of 0.4.2
