### ISSUE TITLE
Installing with Administrative Permissions

### ISSUE THREAD

**Issue by whatasunnyday** [LinusU/node-appdmg#73]
I'm writing a GUI application with electron that requires root permissions to modify /etc/hosts. Based on the following issues, I found myself here:
maxogden/electron-packager#87
https://github.com/loopline-systems/electron-builder/issues/52#issuecomment-152846489 (same message as this issue)

Is it possible use this installer to ask for administrative permissions?

I believe that this would be a great feature. I've seen it asked for in the following places (without a satisfactory solution):
https://discuss.atom.io/t/performing-actions-that-require-superuser-privileges/16892
https://discuss.atom.io/t/start-application-with-root/18815

**Comment by LinusU** [comment]
This is actually not a installer at all, it's just a tool for creating `.dmg` disk images. Unfortunately, you'll have to look for your solution elsewhere...

**Comment by whatasunnyday** [comment]
Thanks for the prompt response @LinusU. Sorry to bother!

**Comment by LinusU** [comment]
No problem :)
