### ISSUE TITLE
Parsing JSON Specification Error

### ISSUE THREAD

**Issue by vikramiyer** [LinusU/node-appdmg#74]
I get this error "Unexpected token /"

The error is not intuitive. Please elaborate the error message

**Comment by LinusU** [comment]
Try pasting your json into [JSONLint](http://jsonlint.com) to get better error messages.

This error comes from V8/Node.js, it would be awesome if it where better though. It is fixable in userland but I think it's a bit too much work for the small benefit.

**Comment by temmink** [comment]
you have to remove the // comments in the appdmg.json file.
Then it will finished with that error-message.
How-ever I still have an error-message at stage 19 "Finalizing image...     FAIL"

**Comment by havenchyk** [comment]
Can be closed. /cc @LinusU
