### ISSUE TITLE
Improving docs on what properties are required

### ISSUE THREAD

**Issue by stefanjudis** [LinusU/node-appdmg#76]
Hey,

as pointed out here

https://github.com/loopline-systems/electron-builder/issues/69

`appdmg` does not work without setting the background image.

Can you maybe confirm that and maybe we can improve the documentation with *required*  marks for the attributes? I'd guess some of the options are not mandatory. :bowtie: 

Thanks. :)

**Comment by LinusU** [comment]
Tracking this in #69 as well, I would like it for the background to be optional.

I think that the specific problem related to your bug report was that the background was specified ("/Library/WebServer/Documents/hummingbird/assets/osx/background.png"), but wasn't found.

We should absolutely update the documentation to indicate which fields is mandatory and which are optional.

**Comment by LinusU** [comment]
Actually, we could probably make all the options optional and than document that...

**Comment by stefanjudis** [comment]
True about:

> `("/Library/WebServer/Documents/hummingbird/assets/osx/background.png")`

but it was a different case - where I messed up the file paths. ;)

Improving docs sound really good. :+1: 

Thx.
