### ISSUE TITLE
Some Background Images silently fail (some JPGs, PNGs, TIFFs)

### ISSUE THREAD

**Issue by jleaders** [LinusU/node-appdmg#77]
I noticed `appdmg` will not load my background image I created.

I have a theory it is due to your image loader not supporting standard compression settings, but I'm not sure. Some images work. Some images don't. I have attached two images: one working, one not working. The second was simply created by opening the working image in GIMP (free image editor), drawing on it, and then exporting as a JPG with default settings.

To reproduce: try to create a DMG with works.jpg (attached), note it works, then again with fails.jpg and note,  it results in a pure white background in the DMG.

**works.jpg**
![works](https://cloud.githubusercontent.com/assets/2430917/11255742/b7161fa6-8dfc-11e5-860d-ed8280e30d51.jpg)

**fails.jpg**
![fails](https://cloud.githubusercontent.com/assets/2430917/11255741/b6fbdd6c-8dfc-11e5-8e2a-75933fe27cf3.jpg)

**Comment by jleaders** [comment]
God I'm a moron, lol it was the location of the image being in the wrong place. False alarm, never mind.

**Comment by LinusU** [comment]
:ok_woman:
