### ISSUE TITLE
Hide sidebar and toolbar in installer

### ISSUE THREAD

**Issue by havenchyk** [LinusU/node-appdmg#79]
Hi, @LinusU!

After building the installer on MacOS with node-appdmg  I see this image. Is there a way to hide sidebar and toolbar? I haven't found solution so far. Maybe the problem is in `.DS_STORE`?

![img](https://camo.githubusercontent.com/42bff7f27b95912e0cdb5f0f1c2946ceac9a113c/687474703a2f2f692e696d6775722e636f6d2f567a5179436f342e706e67)

**Comment by havenchyk** [comment]
Hey, @LinusU  have you a chance to take a look?

**Comment by LinusU** [comment]
I haven't been able to reproduce it, could you upload a dmg that exhibits the problem?

**Comment by havenchyk** [comment]
@LinusU let me try to build once again, I can't upload dmg because of NDA.

**Comment by LinusU** [comment]
You can replace the app with the dummy app from this repo. Actually you could just try and build the provided example and see if that works...

**Comment by havenchyk** [comment]
Heh, working now, I'm not sure, what is was.

**Comment by gera2ld** [comment]
I have met this issue too, is there any programmatic way to hide them now?
