### ISSUE TITLE
Fails on windows and linux

### ISSUE THREAD

**Issue by havenchyk** [LinusU/node-appdmg#80]
Hi, when I'm trying to install this package on linux or windows, it throws an exception. But if I use node-appdmg as a dependency in the another package, it's a problem. Why do you throw an exception instead of just printing warning message?

**Comment by LinusU** [comment]
I'm throwing an exception because it dosen't work on any other platform than OS X. Printing a warning message would just make it throw an exception a few seconds later.

See #14 for status on cross platform support
