### ISSUE TITLE
Any plan to support localized license and background image?

### ISSUE THREAD

**Issue by sainianil** [LinusU/node-appdmg#81]
<h1>Following are the steps to localized license:</h1>[Stackoverflow link](http://stackoverflow.com/questions/367751/creating-a-dmg)

* Download ['Software Licensing for UDIF'](http://adcdownload.apple.com/Developer_Tools/software_licensing_for_udif/slas_for_udifs_1.0.dmg) dmg from your Apple Developer account.
* Double click mount the disk image
* Type below command in Terminal:
   
        cd /Volumes/SLAs_for_UDIFs_1.0
        DeRez SLAResources > ~/Desktop/sla.r```

It will generate localized license file.
* Edit ~/Desktop/sla.r in a text editor, update the content of the data 'TEXT' (5000, "English SLA") resource to  new licensing text.
* Unflatten the disk image file using below command in Terminal:

        hdiutil unflatten installer_image.dmg

* Add the edited license resources to the image using Terminal command:

        Rez -a Z/Desktop/sla.r -o installer_image.dmg

<h2>I have two issues after following above steps:</h2>
1. By default license is displayed in french.
2. Edited text is not appeared in license.

**Comment by LinusU** [comment]
I don't think that it's possible to implement localized background images...

License isn't implemented at all currently, pull requests welcome!

**Comment by jssuttles** [comment]
Posting some resources:
https://developer.apple.com/library/mac/technotes/tn2206/_index.html
https://developer.apple.com/library/mac/documentation/Darwin/Reference/ManPages/man1/codesign.1.html
https://github.com/nwjs/nw.js/issues/616

**Comment by cstruct** [comment]
Closing this as background images can't be localized. Localized licences is tracked in issue #111.
