### ISSUE TITLE
title not showing on created image

### ISSUE THREAD

**Issue by chrismccoy** [LinusU/node-appdmg#82]
the title is not shown at the top of the dmg window, only on the path bar at the bottom.

**Comment by LinusU** [comment]
Do you have a screenshot?

**Comment by LinusU** [comment]
Closing pending more info...

**Comment by chrismccoy** [comment]
i think it is a osx 10.10 and 10.11 thing, title is no longer used in dmg at the top of the dmg, only an icon is shown, title is shown at bottom though. so its not to do with your node module
