### ISSUE TITLE
Window generated for DMG is shorter than background image

### ISSUE THREAD

**Issue by avoidwork** [LinusU/node-appdmg#83]
Hi,

Thanks for making this awesome module; super time saver! I have a problem, which is confusing me a bit. The background image is 449x230 which `image-size` detects properly, and is also set properly at line (approx) line 283: ```global.bkgsize = [value.width, value.height]```, however the resulting window is actually 202px for the content.

Default size output:
![screen shot 2016-01-11 at 2 12 11 pm](https://cloud.githubusercontent.com/assets/369698/12243831/8fe26f1a-b86e-11e5-8c11-7879a5c9c9cf.png)

Resized the window to uncover the entire graphic:
![screen shot 2016-01-11 at 2 21 43 pm](https://cloud.githubusercontent.com/assets/369698/12243854/af18ceec-b86e-11e5-8a01-fc3363cee63b.png)

**Comment by LinusU** [comment]
Hmm, it's probably because your finder is displaying the visible bars at the top and the bottom. I haven't seen them that much before, is it some setting that you have set to display them?

**Comment by avoidwork** [comment]
No, but that came up in convo with the designer; we're running different versions of OSX. I'm running 10.11.2, he's on 10.10.x and doesn't see those bars.

I run 10.11.3-beta on another machine, and also see the bars there, so it's probably some new for OSX.

**Comment by tunabelly** [comment]
There's an option in the Finder to show/hide the status bar.  Click the View menu and choose "Show/Hide Status Bar".
<img width="235" alt="screen shot 2016-01-11 at 6 54 25 pm" src="https://cloud.githubusercontent.com/assets/2223932/12250437/d1159158-b894-11e5-9562-088121867ca6.png">

**Comment by LinusU** [comment]
Unfortunately I don't think that there is anything we can do about it. Unless the `.DS_Store` can override the "Show status bar" setting, there is now way to know how large the visible portion of the window will end up being.

If there is any indication that this is possible, I will be happy to reopen this and try to fix it!
