### ISSUE TITLE
set size of the mount app window

### ISSUE THREAD

**Issue by hp011235** [LinusU/node-appdmg#94]
Hello,

How can I set the size of the window which shows the MyApp.app to drag to Applications directory?
Currently, I am facing a problem where the window is too big and my background and icons are sitting in the corner of that window.
I was not able to find anything specific related to that in the wiki.

Thanks!
-Hetal

**Comment by LinusU** [comment]
Hmm, the size should be automatically set to the size of the image. Could you post your background image here so that I can debug?

**Comment by hp011235** [comment]
Sorry for the delayed reply @LinusU. Please find the file attached.
Here are my params in package.json
```json
"contents": [
        {
          "x": 350,
          "y": 180,
          "type": "link",
          "path": "/Applications"
        },
        {
          "x": 100,
          "y": 180,
          "type": "file"
        }
      ]
```
![background](https://cloud.githubusercontent.com/assets/7158776/15230793/6b49e8c0-184c-11e6-9a7b-48cd079a7276.png)

**Comment by LinusU** [comment]
The size of the window is the same size as the image. If you want to have a retina background image, you need to provide both a normal scaled one, and a retina version.

Please read the following part of the readme: [Retina Background](https://github.com/LinusU/node-appdmg#retina-background)

**Comment by hp011235** [comment]
Thanks for your help on this @LinusU. However, when I add the image with `@2x` as a Retina Background; it adjusts the window size accordingly; however the background (window) seems approx. 1.5 times bigger than the previous case. Hence, the coordinates (x,y) will change for both the App and /Applications.

I wonder how can we set coordinates for both retina as well as non-retina backgrounds at the same time.

**Comment by LinusU** [comment]
@hp011235 Can you send me both of the background files?

**Comment by hp011235** [comment]
I didn't do much except renaming the same file (attached above) with `@2x`.

**Comment by LinusU** [comment]
You need to downsize the normal file to half the size of the 2x image

**Comment by hp011235** [comment]
I see. So, basically; I need to find the perfect size which will suffice both the retina as well as non-retina displays? Any recommended dimensions?

**Comment by LinusU** [comment]
Well, retina displays will display 2x2 pixels per one normal pixels, so just pick a good size on your own monitor and scale appropriately.

e.g. the picture you uploaded seems to be `894` × `576`, the non-retina version of that would be `447` x `288`. That's a bit small but it's by all means usable.

I've found that a icon-size of 80 and a window size of `640` x `480` works really well. You can try it out by making one image that's `640` x `480`, and another one that's exactly `1280` x `960` which you'll save with the `@2x` postfix.

**Comment by hp011235** [comment]
Awesome! Thank you for clarifying that.
