### ISSUE TITLE
Option to set background color

### ISSUE THREAD

**Issue by sindresorhus** [LinusU/node-appdmg#95]
I don't need any background image. I just want to change the background color.

Seems like it is possible: https://github.com/LinusU/node-ds-store/blob/80673a3528f374379b985a657768c9303f72205b/lib/entry.js#L143-L145

And the Python version `dmgbuild` supports this too: http://dmgbuild.readthedocs.io/en/latest/settings.html#disk-image-settings

**Comment by LinusU** [comment]
Sounds good, pull request welcome

**Comment by develar** [comment]
All changes in the node-appdmg — https://github.com/develar/node-appdmg/commit/2c77aa933ed1f01321081d0848173dc6d4213a28

But after that you will get error in the ds-store module. I gave up (was not major for me). Anyone can grab my patch and continue this work.

**Comment by sindresorhus** [comment]
@develar It needs to be made an option in the `ds-store` module first, as https://github.com/LinusU/node-ds-store/blob/80673a3528f374379b985a657768c9303f72205b/lib/entry.js#L141 needs to be `0` when nothing, and `1` when color. See https://bitbucket.org/al45tair/dmgbuild/src/b08746ed79385ccc512cc23342cf698c5ba0bd3e/dmgbuild/core.py?at=default&fileviewer=file-view-default#core.py-173 for reference.

**Comment by LinusU** [comment]
Released as 0.4.2
